### ISSUE TITLE
Don't reach into build folder of jest-resolve

### ISSUE THREAD

**Issue by SimenB** [arcanis/jest-pnp-resolver#1]
Jest is currently renaming files: https://github.com/facebook/jest/issues/4969

The default resolver should probably be exported from `main`

**Comment by arcanis** [comment]
I think a better option might be for `jest-resolve` to default to either:

- pass the default resolver as an option to the custom resolver, and/or
- use the default resolver when the custom resolver's `module.exports` is not a function

In both of these cases, `jest-pnp-resolver` could then disable itself without having to keep a dependency to `jest-resolve`. How does that sound?

**Comment by SimenB** [comment]
The first one sounds good to me, feels more explicit and allows people to implement a resolver that can fall back to default behavior if they cannot find their module for whatever reason.

**Comment by SimenB** [comment]
Out in 24.1.0

**Comment by arcanis** [comment]
@SimenB fyi I was thinking I could keep the [ugly thing](https://github.com/arcanis/jest-pnp-resolver/blob/master/index.js#L22-L26) until most of the ecosystem switches on Jest 24 (so probably until Jest 25, I'd say). Does that sound ok?

**Comment by SimenB** [comment]
Sure! However, you can check if you get it passed in now, and only do your `require` if not?

**Comment by arcanis** [comment]
Hmm that might work yeah - it adds a slight indirection but it shouldn't be a big deal in most cases 👍

**Comment by terwort** [comment]
Hey guys, I'm trying to update to jest 24, and I'm getting the error about how it can't find the old path (default_resolver). I saw in index.js you implemented the [ugly thing](https://github.com/arcanis/jest-pnp-resolver/blob/master/index.js#L22-L26), but in your latest release, 1.0.2, this code isn't there. Any chance the fix will get released soon?

**Comment by terwort** [comment]
Ahh.. just noticed you referenced a PR that will close this problem. Any idea on release time?

**Comment by arcanis** [comment]
@terwort I've just merged and released the change as 1.1.0 - can you confirm the fix? Seems to work for me.

**Comment by terwort** [comment]
@arcanis I can confirm it is fixed! Thank you very much for your fast delivery 😄
