### ISSUE TITLE
Not working with Jest 24

### ISSUE THREAD

**Issue by lorenzorapetti** [arcanis/jest-pnp-resolver#4]
Just an heads up to let you know that the current version published to npm doesn't include the fix for `jest-resolve`'s default resolver file, which has now a different name since Jest 24.

Is there any chance of getting a new version with this fix?

**Comment by arcanis** [comment]
Sure! I can take a look on Monday, or look at a PR if you prefer 😊

**Comment by SimenB** [comment]
Let's try to fix this properly via https://github.com/arcanis/jest-pnp-resolver/issues/1

**Comment by SimenB** [comment]
24.1.0 of jest is out which provides the default resolver as an argument to custom ones
