### ISSUE TITLE
Error: Cannot find module 'jest-resolve/build/default_resolver'

### ISSUE THREAD

**Issue by NaciAkce** [arcanis/jest-pnp-resolver#5]
Hi 
i get this Error if i try to run jest 
'Error: Cannot find module 'jest-resolve/build/default_resolver''

I think this changes are missing in current Version (1.0.2)
https://github.com/arcanis/jest-pnp-resolver/commit/bdc282606aa9676707ba5448024aaca9f4ecbfea

**Comment by arcanis** [comment]
Thanks for the report! It's a duplicate from #4, the path has to be updated (and use the new `defaultResolver` parameter for modern Jest releases)
